### ISSUE TITLE
Starting from monday (instead of sunday)?

### ISSUE THREAD

**Issue by jmuheim** [lubieniebieski/bootstrap-datetimepicker-rails#1]
Thanks a lot, this really came at the perfect time for our project! :)

Is there an option to display monday first (instead of sunday)?

**Comment by lubieniebieski** [comment]
hey! please check out the plugin's documentation https://github.com/tarruda/bootstrap-datetimepicker/, I think your questions should be posted there, this gem just includes the plugin into asset pipeline, I can't do much here.

**Comment by jmuheim** [comment]
Okay, thank you!
