### ISSUE TITLE
bootstrap.less wasn't found

### ISSUE THREAD

**Issue by ninajlu** [lubieniebieski/bootstrap-datetimepicker-rails#10]
I used the twitter-bootstrap-rails gem and don't have a bootstrap_and_override.scss but a bootstrap_and_overrides.css.less file. When I tried to put
@import 'bootstrap';
@import 'bootstrap-datetimepicker';
into that file, it resulted in an error that said bootstrap.less wasn't found and bootstrap-datetimepicker.less wasn't found. 
How do I fix this issue?

**Comment by akaghzi** [comment]
i have the same issue, i did not put @import 'bootstrap' since i already have an entry 
@import "twitter/bootstrap/bootstrap";

**Comment by lubieniebieski** [comment]
hi guys, if you have `@import "twitter/bootstrap/bootstrap";` then it's ok to skip `@import "bootstrap";`

in order to import the css file into less you can try:

``` scss
@import 'bootstrap-datetimepicker.css';
```

**Comment by akaghzi** [comment]
unfortunately it still gives error:
'bootstrap-datetimepicker.less' wasn't found.

  (in /Users/akaghzi/Project/myh/app/assets/stylesheets/bootstrap_and_overrides.css.less)

**Comment by joost** [comment]
This is because of http://stackoverflow.com/questions/11196915/import-css-file-into-less-file.
Fix it by simply including the CSS in your Rails application.css manifest file by adding:

```
*= require bootstrap-datetimepicker
```

**Comment by joost** [comment]
BTW.. would be good to add this to the README so also less users can use https://github.com/lubieniebieski/bootstrap-datetimepicker-rails.

**Comment by lubieniebieski** [comment]
added, thanks @joost!
