### ISSUE TITLE
Specifying data format with simple_form

### ISSUE THREAD

**Issue by gwuix2** [lubieniebieski/bootstrap-datetimepicker-rails#11]
We have this issue with simple_Form:

http://stackoverflow.com/questions/16784543/specifying-data-format-in-rails-for-simpleform-and-boostrap-datetime-picker

Could you help us solve this please?.

**Comment by gwuix2** [comment]
Got solved. :)

**Comment by lubieniebieski** [comment]
did you try the way presented in [this comment](https://github.com/lubieniebieski/bootstrap-datetimepicker-rails/pull/5#issuecomment-18614145) maybe?

**Comment by gwuix2** [comment]
No, but got it working. But thanks for the gem and for the support!
