### ISSUE TITLE
Twitter Bootstrap 3 

### ISSUE THREAD

**Issue by antsav** [lubieniebieski/bootstrap-datetimepicker-rails#15]
please make compatible with latest bootstrap 3 and it's glyphicons http://getbootstrap.com/components/#glyphicons

thank you

**Comment by lubieniebieski** [comment]
I think the issue you're mentioning should go to the original plugin issues https://github.com/tarruda/bootstrap-datetimepicker/issues. this gem provides only a convenient way to get the plugin inside your app.

**Comment by danhawkins** [comment]
I made this gem compatible on my bootstrap3 branch https://github.com/danhawkins/bootstrap-datetimepicker-rails
