### ISSUE TITLE
defaults preventing data attributes from being assigned

### ISSUE THREAD

**Issue by mfrederickson** [lubieniebieski/bootstrap-datetimepicker-rails#7]
It looks like when you specify a data-date-startdate attribute, it is not read because the logic in the code says to 

```
this.setStartDate(options.startDate || this.$element.data('date-startdate'));
```

but the options are defaulted as 

```
$.fn.datetimepicker.defaults = {
  maskInput: false,
  pickDate: true,
  pickTime: true,
  pick12HourFormat: false,
  pickSeconds: true,
  startDate: -Infinity,
  endDate: Infinity,
  collapse: true
};
```

and `-Infinity` is true, so the rest of the expression is not evaluated.

**Comment by lubieniebieski** [comment]
hey, thanks for your contribution, but this repository contains only the structure needed to use the plugin within rails env.

the issues you've mentioned should go to the original plugin issues https://github.com/tarruda/bootstrap-datetimepicker/issues.
